server:
  servlet:
    context-path: /api
spring:
  hibernate:
    ddl-auto: none
  datasource:
    url: { DATABASE_URL }
    username: { DATABASE_USERNAME }
    password: { DATABASE_PASSWORD }
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: status



